version: '3.8'

services:
  # 前端服务
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: leafpan-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - leafpan-network
    restart: unless-stopped

  # 后端服务
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: leafpan-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=leafpan
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=root123
    depends_on:
      - mysql
    networks:
      - leafpan-network
    restart: unless-stopped

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: leafpan-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=leafpan
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - leafpan-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  leafpan-network:
    driver: bridge