apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: leafpan
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJjcnBpLWtjemN6ZXNybWd4b2s2a2UuY24taGFuZ3pob3UucGVyc29uYWwuY3IuYWxpeXVuY3MuY29tIjogewoJCQkiYXV0aCI6ICJhVzVqYjNKclpYSjBaWE4wTG1OdmJRPT0iCgkJfQoJfQp9Cg==
---
# 注意：上面的.dockerconfigjson需要替换为实际的Base64编码的Docker配置
# 可以使用以下命令生成：
# kubectl create secret docker-registry acr-secret \
#   --docker-server=registry.cn-hangzhou.aliyuncs.com \
#   --docker-username=your-username \
#   --docker-password=your-password \
#   --namespace=leafpan \
#   --dry-run=client -o yaml