version: '3.8'

services:
  # 后端服务
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: leafpan-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/leafpan
      - SPRING_DATASOURCE_USERNAME=leafpan
      - SPRING_DATASOURCE_PASSWORD=leafpan123
    volumes:
      - ./logs/backend:/app/logs
    depends_on:
      - mysql
    networks:
      - leafpan-network

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: leafpan-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - leafpan-network

  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: leafpan-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: leafpan
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - leafpan-network

networks:
  leafpan-network:
    driver: bridge

volumes:
  mysql_data: